apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - name: server-container
        image: sflorenz05/drt:server
        imagePullPolicy: Always
        env:
        - name: DB_URL
          value: http://db-container:8081/
        ports:
        - containerPort: 8082
      - name: db-container
        image: sflorenz05/drt:db
        imagePullPolicy: Always
        ports:
        - containerPort: 8081