strict.perms: false

filebeat.inputs:
- type: filestream
  id: suricata-filestream
  enabled: true
  paths:
    - /var/log/suricata/eve.json
  parsers:
    - ndjson:
        keys_under_root: true
        overwrite_keys: true
        message_key: "message"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"